<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama panggilan Mom_form_daftar_nick_name</name>
   <tag></tag>
   <elementGuidId>5cd2bc78-e3ce-4185-9849-656394223125</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#form_daftar_nick_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='form_daftar_nick_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f235eeef-ba60-45f6-858c-cf00cb14c1fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>nickname</value>
      <webElementGuid>925d8734-d212-4491-bce8-35b1c7dabbb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukan nama panggilan Mom</value>
      <webElementGuid>f86eafd3-1e36-4550-bde1-b458224d8577</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b28219f3-acd3-4019-b452-db2c07e9e66e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form_daftar_nick_name</value>
      <webElementGuid>8c8b62a6-32fe-42c5-8f9c-c015f23cb914</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-__meta</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>35f354ac-746b-4081-91fb-5b28e79a1825</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-__field</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>fc838347-e9b2-401d-9f5b-e48737af650e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input ant-input-lg</value>
      <webElementGuid>70bd0f4d-4734-4454-be6e-e1a23d832440</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_daftar_nick_name&quot;)</value>
      <webElementGuid>1deda971-fec4-4d04-8d37-d60e2d5c4bcd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='form_daftar_nick_name']</value>
      <webElementGuid>dbedec96-105d-478c-9582-146a2ed4e0e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/div[2]/div/div[2]/div/form/div[4]/div[2]/div/span/span/input</value>
      <webElementGuid>e0ff5689-c31c-4e1e-8e49-19cd607a4995</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/span/span/input</value>
      <webElementGuid>c1a25321-6e17-40d4-a539-b728030f86ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Masukan nama panggilan Mom' and @type = 'text' and @id = 'form_daftar_nick_name']</value>
      <webElementGuid>5e32eee6-c88e-441b-b8dc-510073b0c0bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
