<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>fb945656-39f3-4c0f-832a-337ad880bdc5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.example > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>3a949ef8-fcd9-4dfd-b3f3-7e8db5c60db8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>asdf.jpg</value>
      <webElementGuid>66ab3c22-37e7-48c1-aea7-bf775c4be00b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;example&quot;]/img[1]</value>
      <webElementGuid>06104a27-99f1-4f7b-9ea5-1981847043e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/img</value>
      <webElementGuid>ccdd23a8-d82b-4d7a-a5d4-01de45c7794a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>61135e7b-e139-4b1d-a6f3-cf39efb1988d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'asdf.jpg']</value>
      <webElementGuid>09e029ab-6aae-46f5-815b-3b5dcdee7d71</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
