<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Ingin mendapatkan informasi terbaru dari RuangmomAktifkan notifikasi sekarang.AktifkanLain kali</name>
   <tag></tag>
   <elementGuidId>b1f6801f-d5da-4d50-bfa3-b3dcec860bd6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#onesignal-slidedown-dialog</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='onesignal-slidedown-dialog']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>94db8121-e25e-4bd9-b685-1c7a9d2c33d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>onesignal-slidedown-dialog</value>
      <webElementGuid>ed2133c5-7af2-4fad-a1b1-b6f106f83d33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>onesignal-slidedown-dialog</value>
      <webElementGuid>9cf93570-eefb-4f0b-ab5b-05328be16fdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ingin mendapatkan informasi terbaru dari Ruangmom?Aktifkan notifikasi sekarang.AktifkanLain kali</value>
      <webElementGuid>584ec600-fbba-49d4-bbce-e34499edb809</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;onesignal-slidedown-dialog&quot;)</value>
      <webElementGuid>bd7386d9-1979-40cc-939a-a341f9c48183</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='onesignal-slidedown-dialog']</value>
      <webElementGuid>fe85c815-1b1e-4831-ab69-82014fc4557d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='onesignal-slidedown-container']/div</value>
      <webElementGuid>16b72af2-64e7-4351-8990-ad209c6f994b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'onesignal-slidedown-dialog', '&quot;', ')')])[1]/following::div[3]</value>
      <webElementGuid>ffa58a0a-2f7a-462e-97d9-b665834415d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::div[4]</value>
      <webElementGuid>2ac7afd9-4e44-496e-8553-cc8e5a34c45a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div</value>
      <webElementGuid>241ce0d8-2c7c-4141-bdca-7651ad1f926c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'onesignal-slidedown-dialog' and (text() = 'Ingin mendapatkan informasi terbaru dari Ruangmom?Aktifkan notifikasi sekarang.AktifkanLain kali' or . = 'Ingin mendapatkan informasi terbaru dari Ruangmom?Aktifkan notifikasi sekarang.AktifkanLain kali')]</value>
      <webElementGuid>022a5f3c-ff63-46bd-a6a5-e5327b6ffb2c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
