<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verif2</name>
   <tag></tag>
   <elementGuidId>28dffa28-bdaa-4c12-ab53-b2c540201ac4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ant-modal-body</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Dapatkan aplikasi Ruangmom'])[2]/following::div[10]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>aa399bca-e8ee-48f6-959f-dad370270c69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-modal-body</value>
      <webElementGuid>47fda782-0e23-4fb4-a33a-ea277b4c43c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Buat akun Ruangmom, yuk!Mom bisa menikmati berbagai konten, events, fitur kalkulator, dan juga fitur shopping secara maksimal.Buat Akun SekarangSudah punya akun? Masuk di sini ya Mom.</value>
      <webElementGuid>ae8d1c31-24a3-45c7-a519-6e1d4a90f4af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;ant-scrolling-effect&quot;]/div[3]/div[@class=&quot;ant-modal-root&quot;]/div[@class=&quot;ant-modal-wrap ant-modal-centered&quot;]/div[@class=&quot;ant-modal modal-rm modal-signup&quot;]/div[@class=&quot;ant-modal-content&quot;]/div[@class=&quot;ant-modal-body&quot;]</value>
      <webElementGuid>77a024eb-72c8-4a68-ad8c-f04ab1c696cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dapatkan aplikasi Ruangmom'])[2]/following::div[10]</value>
      <webElementGuid>549ebabc-1faf-484f-9cc1-b220817dde47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EightyEight @Kasablanka Tower A, 10 floor Unit EJl. Raya Casablanca Kav. 88 Jakarta 12870'])[1]/following::div[11]</value>
      <webElementGuid>867c0f16-a302-43d6-8d4f-a18b3421677a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div[2]/div</value>
      <webElementGuid>53b5d58a-2f0f-47d3-9f58-6ce50efb9bc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Buat akun Ruangmom, yuk!Mom bisa menikmati berbagai konten, events, fitur kalkulator, dan juga fitur shopping secara maksimal.Buat Akun SekarangSudah punya akun? Masuk di sini ya Mom.' or . = 'Buat akun Ruangmom, yuk!Mom bisa menikmati berbagai konten, events, fitur kalkulator, dan juga fitur shopping secara maksimal.Buat Akun SekarangSudah punya akun? Masuk di sini ya Mom.')]</value>
      <webElementGuid>eda4651d-4308-4c00-acda-62a4995fc101</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
