<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_sample-zip-file.zip</name>
   <tag></tag>
   <elementGuidId>ff86eed6-14ec-4f90-8442-61f251438868</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.example > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fd78c323-a717-4302-9231-0edc85872551</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>download/sample-zip-file.zip</value>
      <webElementGuid>733cc5f4-87df-49a0-a598-98b3e742439a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>sample-zip-file.zip</value>
      <webElementGuid>7cc7ca7d-b5c6-4687-970a-bc4e5f4203ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;example&quot;]/a[1]</value>
      <webElementGuid>22f802cc-1717-4409-80c5-18f395b3f945</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/a</value>
      <webElementGuid>caa3c207-f095-4000-b986-ebe68593f1b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'sample-zip-file.zip')]</value>
      <webElementGuid>cada61dd-953a-4a2c-88b8-a7e573418e7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='File Downloader'])[1]/following::a[1]</value>
      <webElementGuid>5b4ea6e1-0625-47f0-98b9-8b27a9df9ae8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HRMS Assesment.txt'])[1]/preceding::a[1]</value>
      <webElementGuid>cb1beb43-b37b-4374-b22c-10520a36290e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ScreenShot.png'])[1]/preceding::a[2]</value>
      <webElementGuid>b41a5e39-4230-461f-91aa-9282667369c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='sample-zip-file.zip']/parent::*</value>
      <webElementGuid>17f54de2-0b70-49b9-8d9c-c7775b234a7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'download/sample-zip-file.zip')]</value>
      <webElementGuid>173a0894-0b42-4020-91d1-b087aa1978e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/a</value>
      <webElementGuid>073229d9-b9f8-47bf-9ede-e107748cb593</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'download/sample-zip-file.zip' and (text() = 'sample-zip-file.zip' or . = 'sample-zip-file.zip')]</value>
      <webElementGuid>25f7d376-fba4-46e9-96a7-6b900384f411</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
