<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_E-mail sudah terdaftar, silahkan coba dengan alamat e-mail lain ya Mom vyt</name>
   <tag></tag>
   <elementGuidId>72730763-a9ca-461f-ba88-547a29245abc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div/div[2]/div/div[2]/div/form/div/div[2]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ant-form-explain</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>60ed22bf-a071-48e7-abc5-5e7c435de16a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-form-explain</value>
      <webElementGuid>496c9856-9e9e-47c7-b880-64b135929051</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>E-mail sudah terdaftar, silahkan coba dengan alamat e-mail lain ya Mom vyt</value>
      <webElementGuid>2731a6ce-41f5-4752-b635-80d0c65c4d7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;ant-row&quot;]/div[@class=&quot;ant-col ant-col-24&quot;]/div[@class=&quot;ant-row mb-5&quot;]/div[@class=&quot;ant-col ant-col-xs-22 ant-col-xs-offset-1 ant-col-sm-18 ant-col-sm-offset-3 ant-col-md-20 ant-col-md-offset-2 ant-col-lg-22 ant-col-lg-offset-1 ant-col-xl-18 ant-col-xl-offset-3&quot;]/div[@class=&quot;ant-row-flex container&quot;]/div[@class=&quot;ant-col ant-col-xs-order-1 ant-col-sm-order-1 ant-col-md-12 ant-col-md-order-2 ant-col-lg-12 ant-col-lg-order-2 ant-col-xl-12 ant-col-xl-order-2&quot;]/div[@class=&quot;infograph rmform mt-30 article--oldhover widget-signup&quot;]/div[@class=&quot;ant-row&quot;]/div[@class=&quot;ant-col pb-4 ant-col-md-20 ant-col-md-offset-2 ant-col-lg-20 ant-col-lg-offset-2 ant-col-xl-20 ant-col-xl-offset-2&quot;]/form[@class=&quot;ant-form ant-form-horizontal ant-form--custom&quot;]/div[@class=&quot;ant-row ant-form-item ant-form-item-with-help&quot;]/div[@class=&quot;ant-col ant-form-item-control-wrapper&quot;]/div[@class=&quot;ant-form-item-control has-error&quot;]/div[@class=&quot;ant-form-explain&quot;]</value>
      <webElementGuid>c26b0d40-9e4f-4174-8e82-37a0dbc00545</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/div[2]/div/div[2]/div/form/div/div[2]/div/div</value>
      <webElementGuid>1c21a5ee-55ea-4f6a-9b8f-62640c2c1258</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E-mail'])[1]/following::div[3]</value>
      <webElementGuid>ecde345c-e236-4b21-8ce7-57204687863c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar menggunakan e-mail'])[1]/following::div[7]</value>
      <webElementGuid>d632ecd7-1a04-46ed-acd0-a1cb6240ca49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kata Sandi'])[1]/preceding::div[1]</value>
      <webElementGuid>dbc4d1b7-6663-4fef-ace3-9100fa108c46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ulangi Kata Sandi'])[1]/preceding::div[5]</value>
      <webElementGuid>f5544d0a-fe56-4c97-9a3e-307880fa5993</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='E-mail sudah terdaftar, silahkan coba dengan alamat e-mail lain ya Mom vyt']/parent::*</value>
      <webElementGuid>f7698577-b049-457c-ada3-4f19d8725d8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]/div/div</value>
      <webElementGuid>eee029bd-0d5f-45e6-854c-191d7d584d50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'E-mail sudah terdaftar, silahkan coba dengan alamat e-mail lain ya Mom vyt' or . = 'E-mail sudah terdaftar, silahkan coba dengan alamat e-mail lain ya Mom vyt')]</value>
      <webElementGuid>afd75601-523c-4a14-b5e1-ca00d40a84e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
