<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Daftar Layanan_searchMerchantInput</name>
   <tag></tag>
   <elementGuidId>362c02d5-9dae-4581-9cec-04be338896fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='searchMerchantInput']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#searchMerchantInput</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7cda4899-d3a3-4f7c-aa5c-9207fd161860</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchMerchantInput</value>
      <webElementGuid>2f8f1482-327c-440f-97dd-c5425d9b822e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Cari Nama Layanan...</value>
      <webElementGuid>94f25d00-c965-40fc-abeb-5fcd6b9a97c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input</value>
      <webElementGuid>8ee90371-e43f-4f6b-9cb9-42c9fb924b0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a96198b7-9932-4965-82f0-3fa73b97511d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchMerchantInput&quot;)</value>
      <webElementGuid>f0c3aed5-7d7f-43cf-9079-0c90d21a4a51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='searchMerchantInput']</value>
      <webElementGuid>b918cc68-5f50-4dfc-9c60-ce8047894dba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div[2]/div[2]/span/input</value>
      <webElementGuid>4f8e70a4-995d-46ac-be9b-4ed972f1e109</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>ea5058ef-2795-423a-9e8b-450f2aa95ee4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'searchMerchantInput' and @placeholder = 'Cari Nama Layanan...' and @type = 'text']</value>
      <webElementGuid>16b7d3e5-a3d4-4502-9581-8df7bbd80836</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
