<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg</name>
   <tag></tag>
   <elementGuidId>e374d580-54cf-49d0-b1a3-bba334938881</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>``</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.anticon.anticon-search.ant-input-search-icon > svg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>802eb17b-8f18-4de4-b669-09d17d483466</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 1024 1024</value>
      <webElementGuid>48caa39a-366c-4ca9-8a21-a5644db7487b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focusable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a6fc8a1f-e53c-4164-ae14-12af1ce9bacf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-icon</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>b075376e-744a-4d4a-ac9f-119c5cb19194</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1em</value>
      <webElementGuid>eb3a4415-76e7-4df0-9c1a-65e29b369bac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>1em</value>
      <webElementGuid>27a4b198-44b1-4df2-a6c5-2e338ecef4e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>947d79aa-5ad1-44b5-9327-a4d37f165fe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>41dd7ae4-20f6-4f5e-95a2-dfb1bac719d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;ant-row&quot;]/div[@class=&quot;ant-col ant-col-xs-22 ant-col-xs-offset-1 ant-col-sm-18 ant-col-sm-offset-3 ant-col-md-20 ant-col-md-offset-2 ant-col-lg-22 ant-col-lg-offset-1 ant-col-xl-18 ant-col-xl-offset-3&quot;]/div[@class=&quot;ant-row merchant&quot;]/div[@class=&quot;ant-col ant-col-md-24 ant-col-lg-18&quot;]/div[@class=&quot;merchant__searching&quot;]/span[@class=&quot;ant-input-search ant-input-affix-wrapper&quot;]/span[@class=&quot;ant-input-suffix&quot;]/i[@class=&quot;anticon anticon-search ant-input-search-icon&quot;]/svg[1]</value>
      <webElementGuid>8e39c682-b7ce-423e-a5f0-ee884ea719d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar Layanan'])[3]/following::*[name()='svg'][1]</value>
      <webElementGuid>f5c04546-376f-4d31-b07b-6669cdea4da2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terapkan'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>c7d36bf5-c0a8-4cb9-a2f4-7ee60a8367e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adipka Kids Mom &amp; Baby Spa'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>88a60984-4b47-44d1-bcd7-b8973a92f3c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Spa'])[2]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>b8d01257-da56-4363-985c-e7dfc88e9d79</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
