<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Back</name>
   <tag></tag>
   <elementGuidId>fbd1f81f-9140-47d9-b915-8af21d8c5f5f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Dapatkan aplikasi Ruangmom'])[2]/following::div[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ant-modal-wrap.ant-modal-centered</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9b9d89df-c814-4f5e-bbba-9b9e2132beea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>3f5b66dc-8044-4d72-a61a-2f8d08457ed7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-modal-wrap ant-modal-centered</value>
      <webElementGuid>a753b33a-3ec3-4bc1-8c34-5e3259a157b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>13703310-d0fc-4c16-b504-09956e51b739</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Buat akun Ruangmom, yuk!Mom bisa menikmati berbagai konten, events, fitur kalkulator, dan juga fitur shopping secara maksimal.Buat Akun SekarangSudah punya akun? Masuk di sini ya Mom.</value>
      <webElementGuid>b9164dad-b618-4cfb-8c19-bdd3cb3ed079</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;ant-scrolling-effect&quot;]/div[3]/div[@class=&quot;ant-modal-root&quot;]/div[@class=&quot;ant-modal-wrap ant-modal-centered&quot;]</value>
      <webElementGuid>3622b331-92f5-4b65-8d98-d51034da2eba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dapatkan aplikasi Ruangmom'])[2]/following::div[6]</value>
      <webElementGuid>bba1898d-39aa-4a38-bbf5-897c2dd4ca25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EightyEight @Kasablanka Tower A, 10 floor Unit EJl. Raya Casablanca Kav. 88 Jakarta 12870'])[1]/following::div[7]</value>
      <webElementGuid>e62ffc02-35d4-4c1b-a914-43a727c785df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]</value>
      <webElementGuid>188e393c-3575-42ad-adee-560b19edee44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Buat akun Ruangmom, yuk!Mom bisa menikmati berbagai konten, events, fitur kalkulator, dan juga fitur shopping secara maksimal.Buat Akun SekarangSudah punya akun? Masuk di sini ya Mom.' or . = 'Buat akun Ruangmom, yuk!Mom bisa menikmati berbagai konten, events, fitur kalkulator, dan juga fitur shopping secara maksimal.Buat Akun SekarangSudah punya akun? Masuk di sini ya Mom.')]</value>
      <webElementGuid>b888d751-504c-4efc-a01e-8f1faf215fcc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
